config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/user_account', to: 'users#index'
  resources :foods, only: [:index, :new, :create, :show, :destroy ]
  resources :recipes, only: [:index, :update, :new, :create, :show, :destroy ] do
  resources :recipe_foods, only: [:update, :new, :create, :destroy ]
  end

  get '/general_shoping_list', to: 'foods#general_shoping_list'
  get '/public_recipes', to: 'recipes#public_recipes'
  root "foods#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :read, Recipe, public: true
    can :manage, Recipe, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id }
  validates :measurement_unit, presence: true
  validates :measurement_unit, inclusion: { in: %w[g kg ml l oz lb] }
  validates :price, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :recipes, dependent: :destroy
  has_many :foods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  # rescue_from CanCan::AccessDenied do |exception|
  #   redirect_to root_url, alert: exception.message
  # end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  def index
    @foods = current_user.foods
  end

  def general_shoping_list
    @foods = Food.all
    @food_items = @foods.length
    @price_sum = Food.sum(:price)
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(user: current_user)
    @food.assign_attributes(food_params)
    if @food.save
      redirect_to foods_path
      flash[:success] =  'Food was successfully created!'
    else
      flash.now[:error] = 'Could not create food, try again'
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @food.update(food_params)
      flash[:success] =  "Measurement unit received: #{params[:food]}"
      redirect_to food_url(@food), notice: 'Food was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Destroy action to delete a food item.
  def destroy
    if @food.destroy
      flash[:success] = 'Food was successfully deleted.'
    else 
      flash[:error] = 'Could not delete food, try again'
    end
    redirect_to foods_url
  end

  private

  # Helper method to set the @food instance variable.
  def set_food
    @food = Food.find(params[:id])
  end

  # Strong parameters to whitelist the allowed attributes for food creation and updates.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @new_ingredient = RecipeFood.new
    @recipe = Recipe.find_by(id: params[:recipe_id])
    @foods = current_user.foods
    render 'new'
  end

  def create
    @recipe = Recipe.find_by(id: params[:recipe_id])
    ingredient = RecipeFood.new(recipe: @recipe)
    ingredient.assign_attributes(recipe_food_params)
    if ingredient.save
      flash[:success] = 'The ingredient was added!'
    else
      flash[:error] = 'Could not add the ingredient, try again'
    end
    redirect_to recipe_path(@recipe)
  end

  def destroy
    ingredient = RecipeFood.find_by(id: params[:recipe_id])
    @recipe = Recipe.find_by(id: params[:id])
    if ingredient.destroy
      flash[:success] = 'The recipe was deleted'
    else
      flash[:error] = 'Could not delete recipe, try again'
    end
    redirect_to recipe_path(@recipe)
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource

  def index
    @recipes = current_user.recipes
    render 'index'
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @ingredients = @recipe.recipe_foods.includes(:food)
    render 'show'
  end

  def new
    @new_recipe = Recipe.new
    render 'new'
  end

  def create
    recipe = Recipe.new(user: current_user)
    recipe.assign_attributes(recipe_params)
    if recipe.save
      redirect_to recipes_path
      flash[:success] = 'The recipe was posted!'
    else
      flash.now[:error] = 'Could not post recipe, try again'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    recipe = Recipe.find_by(id: params[:id])
    if recipe.destroy
      flash[:success] = 'The recipe was deleted'
      redirect_to recipes_path
    else
      flash.now[:error] = 'Could not delete recipe, try again'
    end
  end

  def update
    recipe = Recipe.find_by(id: params[:id])
    if recipe.update_attribute(:public, !recipe.public)
      flash[:success] = 'The visibility was changed sucsessfully'
    else
      flash.now[:error] = 'Could not change visibility, try again'
    end
    redirect_to recipe
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).all
    render 'public_recipes'
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :public, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_alert_class(type)
    case type
    when 'error'
      'alert-warning'
    when 'success'
      'alert-success'
    else
      'alert-secondary'
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.htmml.erb
<tr id="<%= dom_id food %>">
  <td>
    <%= food.name %>
  </td>

  <td>
    <%= food.measurement_unit %>
  </td>

  <td>
    <%= number_to_currency(food.price) %>
  </td>
  
  <td>
    <button class="btn btn-danger" data-confirm="Are you sure?" data-method="delete" onclick="window.location.href='/foods/<%= food.id %>'">
      Delete
    </button>
  </td>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true, class: 'needs-validation', novalidate: true) do |form| %>
  <% if food.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row g-3">
    <div class="col-md-6 mb-3">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control', required: true %>
    </div>
    <div class="col-md-2 mb-3">
      <%= form.label :measurement_unit, class: 'form-label' %>
      <%= form.select :measurement_unit, [["grams", "g"], ["kilograms", "kg"], ["milliliters", "ml"], ["liters", "l"], ["ounces", "oz"], ["pounds", "lb"], ["cups", "c"], ["teaspoons", "tsp"], ["units", "U"]], {}, class: 'form-select', required: true %>
    </div>
    <div class="col-md-2 mb-3">
      <%= form.label :price, class: 'form-label' %><i class="form-text">(In USD)</i>
      <%= form.text_field :price, class: 'form-control', placeholder: '$', required: true %>
    </div>
    <div class="col-md-2 mb-3">
      <%= form.label :quantity, class: 'form-label' %>
      <%= form.number_field :quantity, class: 'form-control', required: true %>
    </div>
    <div class="mb-3">
      <%= form.submit 'Create Food', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= render "form", food: @food %>

<br>

<div class="btn-group">
  <%= link_to "Show this food", @food, class: "btn btn-primary" %>
  <%= link_to "Back to foods", foods_path, class: "btn btn-secondary" %>
</div>

app/views/foods/general_shoping_list.html.erb
<div class="container">
  <h1 class="mt-5">Shopping List</h1>
  <div class="mt-3">
    <span class="me-3">Amount of food items to buy: <span class="text-info"><%= @food_items %></span></span>
    <span>Total value of food needed:  $<span class="text-info"><%= @price_sum %></span></span>
  </div>
  <section class="mt-4">
    <table class="table table-bordered" id="foods">
      <thead class="table-primary">
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td>
              <%= food.name %>
            </td>
            <td>
              <%= food.quantity %>
            </td>
            <td>
              <%= food.price %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/foods/general_shopping_list.html.erb
<br />
<h1>Shopping List</h1>
  <div>
    <span>Amount of food items to buy: <%= @food_items %> </span>
    <span>Total value of food needed: $<%= @price_sum %> </span>
  </div>
<section>
  <table id="foods">
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td>
            <%= food.name %>
          </td>
          <td>
            <%= food.quantity %>
          </td>
          <td>
            <%= food.price %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/foods/index.html.erb
<section>
  <div class="d-flex justify-content-between align-items-center">
    <h1>Foods</h1>
  </div>

  <table class="table table-striped" id="foods">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
  <% @foods.each do |food| %>
    <%= render partial: 'shared/food', locals: { food: food } %>
  <% end %>
</tbody>
  </table>
   <%= link_to "Add Food", new_food_path, class: 'btn btn-primary' %>
</section>

app/views/foods/new.html.erb
<section>
  <div class="d-flex justify-content-between align-items-center">
    <h1>New Food</h1>
    <%= link_to "Back to Foods", foods_path, class: 'btn btn-secondary' %>
  </div>

  <%= render "form", food: @food %>
</section>

app/views/foods/show.html.erb
<section>
  <div class="d-flex justify-content-between align-items-center">
    <h1>Food Details</h1>
    <%= link_to "Back to Foods", foods_path, class: 'btn btn-secondary' %>
  </div>

  <table class="table table-striped" id="foods">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Measurement unit</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <%= @food.name %>
        </td>
        <td>
          <%= @food.measurement_unit %>
        </td>
        <td>
          <%= @food.price %>
        </td>
        <td>
        </td>
      </tr>
    </tbody>
  </table>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>
  <body class="container">
  <%= render partial: "shared/navigation" %>
    <% flash.each do |type, msg| %>
      <div class="alert <%= flash_alert_class(type) %>">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<div class='my-5 pt-5'>
  <h2 class='text-center'>Add ingredient to recipe</h2>
  <%= form_with model: @new_ingredient, url: recipe_recipe_foods_path, method: :post, local: true, scope: :recipe_food do |f| %>
    <div class="row g-3">
      <div class="col-md-4 mb-3">
        <label class="form-label">Recipe</label>
        <input class="form-control" type="text" placeholder="<%= @recipe.name%>" disabled>
      </div>
      <div class="col-md-3 mb-3">
        <label class="form-label" for="food">Select food</label>
        <% food_array = @foods.map { |food| ["#{food.name} #{food.measurement_unit} ", food.id] } %>
        <%= f.select :food_id, food_array, {}, class: "form-select", id: "food" %>
      </div>
      <div class="col-md-2 mb-3">
        <%= f.label :quantity, class: "form-label" %>
        <%= f.number_field :quantity, class: "form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit 'Add ingredient', class:"btn btn-primary mb-3" %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/_add_ingredients.html.erb
<% if can? :manage, recipe %>
  <%= link_to "Add ingredient", new_recipe_recipe_food_path(recipe), class: 'btn btn-primary my-2' %>
<% end %>

app/views/recipes/_delete_ingredient.html.erb
<% if can? :manage, recipe %>
  <%= button_to "Delete ingredient", recipe_recipe_food_path(ingredient), method: :delete, class:'btn btn-sm btn-outline-danger' %>
<% end %>

app/views/recipes/_ingredients_table.html.erb
<div class="card my-5">
  <table class="table table-striped" id="foods">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% ingredients.each do |ingredient| %>
        <tr id="<%= dom_id ingredient %>">
          <td>
            <%= ingredient.food.name %>
          </td>
          <td>
            <%= "#{ingredient.quantity}  #{ingredient.food.measurement_unit}" %>
          </td>
          <td>
            <%= number_to_currency(ingredient.food.price * ingredient.quantity) %>
          </td>
          <td>
            <%= render 'delete_ingredient', ingredient: ingredient, recipe: recipe %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
  <%= render 'shared/recipe', recipe: recipe %>
<%end%>
<div class="text-center mt-5">
  <%= link_to "Add a new recipe", new_recipe_path, class:'btn btn-primary' %>
</div>

app/views/recipes/new.html.erb
<div class='my-5 pt-5'>
  <h2 class='text-center'>Create new recipe</h2>
  <%= form_with model: @new_recipe, url: recipes_path, method: :post, local: true, scope: :recipe do |f| %>
    <div class="row g-3">
      <div class="col-md-6 mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-2 mb-3">
        <%= f.label :preparation_time, class: "form-label" %>
        <%= f.number_field :preparation_time, class: "form-control" %>
      </div>
      <div class="col-md-2 mb-3">
        <%= f.label :cooking_time, class: "form-label" %>
        <%= f.number_field :cooking_time, class: "form-control" %>
      </div>
      <div class="col-md-2 mb-3">
        <label class="form-label" for="visibility">Visibility Preference</label>
        <%= f.select :public, [["Public", "true"], ["Private", "false"]], {}, class: "form-select", id: "visibility" %>
      </div>
      <div class="mb-3">
        <%= f.label :description, class: "form-label" %>
        <%= f.text_area :description, class: "form-control", size: "70x5" %>
      </div>
      <div class="text-center">
        <%= f.submit 'Post recipe', class:"btn btn-primary mb-3" %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes</h1>
<% @public_recipes.each do |recipe| %>
  <%= render 'shared/recipe', recipe: recipe %>
<%end%>

app/views/recipes/show.html.erb
<div class="row">
  <h2 class="text-center col-12"><%= @recipe.name%></h2>
  <div class="col-10 row my-4">
    <h5>Preparation time:  <%= @recipe.preparation_time%> min</h5>
    <h5>Cooking time: <%= @recipe.cooking_time%> min</h5>
  </div>
  <div class="col-2 my-4">
    <%= render 'shared/visibility_toggle', recipe: @recipe%>
  </div>
  <p class="col-12 card p-3"><%= @recipe.description%></p>
  <div class="col-12 d-flex justify-content-between">
    <%= link_to "Generate shopping list", general_shoping_list_path, class: 'btn btn-primary my-2' %>
    <%= render 'add_ingredients', recipe: @recipe%>
  </div>
</div>
<%= render 'ingredients_table', recipe: @recipe, ingredients: @ingredients %>
<%= render 'shared/delete_recipe', recipe: @recipe %>

app/views/shared/_account_icon.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
</svg>

app/views/shared/_delete_recipe.html.erb
<% if can? :manage, recipe %>
  <%= button_to "Delete recipe", recipe_path(recipe), method: :delete, class:'btn btn-sm btn-outline-danger mt-4' %>
<% end %>

app/views/shared/_food.html.erb
<tr id="<%= dom_id food %>">
  <td>
    <%= food.name %>
  </td>
  <td>
    <%= food.measurement_unit %>
  </td>
  <td>
    <%= number_to_currency(food.price) %>
  </td>
  <td>
    <%= button_to "Delete", food_path(food) , method: :delete, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/shared/_navigation.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
  <h1 class="navbar-brand"><a href="/">RECIPE APP</a></h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link nav-link-hover" href="/">Foods</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-hover" href="/recipes">Recipes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-hover" href="/public_recipes">Public Recipe List</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-link-hover" href="/general_shoping_list">Shopping List</a>
      </li>
    </ul>
  </div>
  <% if user_signed_in? %>
    <div class="dropdown">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDropdown" aria-controls="navbarDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarDropdown">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <button class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <%= render "shared/account_icon" %>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class:'btn btn-danger' %>
              </li>
              <li><%= link_to "User account", user_account_path %> </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</header>

app/views/shared/_recipe.html.erb
<div class="card mx-auto my-3">
  <%= link_to recipe_path(recipe), class: "custom-link" do %>
    <div class="card-body row">
      <div class="text-center my-2 col-3">
        <h5 class="card-title"><%= recipe.name%> </h5>
        <%= render 'shared/delete_recipe', recipe: recipe %>
      </div>
      <p class="card-text col-9"><%= recipe.description%> </p>
    </div>
  <% end %>
</div>

app/views/shared/_visibility_toggle.html.erb
<% if can? :manage, recipe %>
  <%= form_with model: recipe do |f| %>
    <div class="form-check form-switch">
      <%= f.check_box :public, class: "form-check-input", role: "switch", id: "visibilitySwitch", checked: @recipe.public, onchange: "this.form.submit();" %>
      <%= f.label :public, class: "form-check-label", for: "visibilitySwitch" %>
    </div>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="pt-5">
  <% if user_signed_in? %>
    <div class="display-6"> Welcome <%= current_user.email %>! </div>
    <div class="row g-3 mt-4">
      <div class="col-md-4 mt-4">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:'btn btn-danger' %>
      </div>
      <div class="col-md-4 mt-4">
        <%= link_to "Update account info", edit_user_registration_path, class:'btn btn-secondary' %>
      </div>
    </div>
  <% else %>
    <div class="h2 text-center">You're not logged in, please log into your account or sign in.</div>
    <div class="my-5 text-center">
      <%= button_to "Sign in", new_user_session_path, class:'btn btn-primary' %>
    </div>
  <% end %>
</div>